# Configuration overrides for deploying istio for testing using proxyv2 image
global:
  nodePort: true
  proxy:
    image: proxyv2

  mtls:
    enabled: false

ingress:
  enabled: false
  service:
    nodePort:
      enabled: true
  autoscaleMin: 1
  autoscaleMax: 8
  meshExpansion:
    enabled: false

# Any customization for istio testing should be here
istiotesting:
  oneNameSpace: false

# needs gateway for testing
ingressgateway:
  enabled: true

egressgateway:
  enabled: false

zipkin:
  enabled: false

sidecar-injector:
  enabled: false
