# instance configuration for template 'metric'
apiVersion: "config.istio.io/v1alpha2"
kind: metric
metadata:
 name: accesslog
 namespace: istio-system
spec:
  value: "1"
  dimensions:
      origin_ip: origin.ip | ip("0.0.0.0")
      origin_uid: origin.uid | ""
      origin_user: origin.user | ""
      # request_headers: request.headers | [""]
      request_id: request.id | ""
      request_host: request.host | ""
      request_method: request.method | ""
      request_path: request.path | ""
      request_reason: request.reason | ""
      request_referer: request.referer | ""
      request_scheme: request.scheme | ""
      request_size: request.size | 0
      request_time: request.time | timestamp("1979-01-01T00:00:00Z")
      request_useragent: request.useragent | ""
      response_code: response.code | 0
      response_duration: response.duration | "-1ms"
      # response_headers: response.headers | [""]
      response_size: response.size | 0
      response_time: response.time | timestamp("1979-01-01T00:00:00Z")
      source_uid: source.uid | ""
      source_user: source.user | ""
      destination_uid: destination.uid | ""
      connection_id: connection.id | ""
      connection_received_bytes: connection.received.bytes | 0
      connection_received_bytes_total: connection.received.bytes_total | 0
      connection_sent_bytes: connection.sent.bytes | 0
      connection_sent_bytes_total: connection.sent.bytes_total | 0
      connection_duration: connection.duration | "-1ms"
      context_protocol: context.protocol | ""
      context_timestamp: context.timestamp | timestamp("1979-01-01T00:00:00Z")
      context_time: context.time | timestamp("1979-01-01T00:00:00Z")
  monitored_resource_type: '"UNSPECIFIED"'
---
# handler configuration for adapter 'metric'
apiVersion: "config.istio.io/v1alpha2"
kind: lumberjack
metadata:
 name: handler
 namespace: istio-system
spec:
 file_path: "/out.json"
---
# rule to dispatch to your handler
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
 name: lumberjack
 namespace: istio-system
spec:
 match: "true"
 actions:
 - handler: handler.lumberjack
   instances:
   - accesslog.metric